Fix https timeout
sozu-proxy/sozu pull request #1067
Opened 2024-01-31 09:11 UTC by Shine-neko

fix https://github.com/sozu-proxy/sozu/issues/787

2024-01-31 09:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sozu-proxy/sozu?pullRequest=1067) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sozu-proxy/sozu?pullRequest=1067) before we can accept your contribution.<br/><hr/>**Mbechezi Mlanawo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sozu-proxy/sozu?pullRequest=1067) it.</sub>

2024-01-31 10:01 UTC, Keksoj requested changes
this is good. can you please change the commit message to be a bit more explicit? for instance, *start_https_worker: send empty listeners* or similarly

2024-01-31 12:15 UTC, Shine-neko commented on lib/src/https.rs
> +        if let Err(e) = scm?.send_listeners(&Listeners {
@Keksoj Listeners has no `default()`.  Should i add a `#[derive(Default)]` ?

2024-01-31 14:48 UTC, Keksoj commented on lib/src/https.rs
> +        if let Err(e) = scm?.send_listeners(&Listeners {
what about this line? `Listeners::default()` works in other places of the code and your commit compiles

https://github.com/sozu-proxy/sozu/blob/66114a495625d4f6d3c2586d39d27b74dc9b426e/command/src/scm_socket.rs#L212-L213

2024-01-31 15:23 UTC, Shine-neko commented on lib/src/https.rs
> +        if let Err(e) = scm?.send_listeners(&Listeners {
this example does not compile https://github.com/Shine-neko/proxie  :thinking:

2024-01-31 15:42 UTC, Keksoj commented on lib/src/https.rs
> +        if let Err(e) = scm?.send_listeners(&Listeners {
the implementation of Default is very recent, your branch on your fork has not fetched it. But it works in the CI ;-)

2024-01-31 15:43 UTC, Keksoj commented
you have renamed the commit `start_https_worker: send empty listeners or similarly` please remove `or similarly` @Shine-neko

2024-01-31 16:01 UTC, Shine-neko commented on lib/src/https.rs
> +        if let Err(e) = scm?.send_listeners(&Listeners {
Ha okay perfect :)

2024-02-01 14:16 UTC, FlorentinDUBOIS commented
@Wonshtrum could you take a look at it?

2024-02-02 09:54 UTC, Wonshtrum commented
Hi @Shine-neko thanks for contributing to Sozu and pointing out the missing `send_listeners` (which blocks the server start). I'm sorry we closed your original issue without proper investigation.
I revisited this old code we never use and found that the TCP proxy had the same problem. To avoid future problems I merged the bulk of the 3 `start_*_worker` functions in `prebuild_server` in #1068. I added you as a co-author I hope this is fine.

2024-02-02 13:31 UTC, Keksoj commented
Closing this for the issue is fixed by #1068 
Thanks for raising our awareness on the issue and your contributing, @Shine-neko !

2024-02-02 13:31 UTC, closed without merging