Fix build of socket.rs on FreeBSD
sozu-proxy/sozu pull request #1075
Opened 2024-02-14 02:25 UTC by yonas

Use OS X code for FreeBSD as well.

Fixes the following build error:
```
error[E0425]: cannot find value `SOL_TCP` in crate `libc`                                                                                                                                                            
   --> lib/src/socket.rs:533:50
    |
533 |         pub const OPT_LEVEL: libc::c_int = libc::SOL_TCP;
    |                                                  ^^^^^^^ not found in `libc`
```

OS: `FreeBSD 14`
Sozu: e451177

2024-02-14 02:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sozu-proxy/sozu?pullRequest=1075) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sozu-proxy/sozu?pullRequest=1075) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sozu-proxy/sozu?pullRequest=1075) it.</sub>

2024-02-14 09:55 UTC, FlorentinDUBOIS commented
Hello @yonas, thanks you for this contribution

2024-02-29 17:29 UTC, Keksoj commented on bin/src/main.rs
> +fn set_workers_affinity(_: &Vec<cli::SubCmd>) {}
please import the Worker type instead. Or is there a reason you switched to this type?

2024-02-29 17:31 UTC, Keksoj commented on bin/src/util.rs
> +    path.extend(std::iter::repeat(0).take(capacity));
can you import those at the top of the file instead?

2024-02-29 17:35 UTC, Keksoj requested changes
i trust it works on your machine.

@fredalix would you have time to check that this branch builds on freebsd? I know you use it :-)

```
sudo pkg install rust
git clone git@github.com:yonasBSD/sozu.git
cd sozu
cargo build
```

Only if you have the time :pray:

2024-03-12 18:51 UTC, closed without merging