import sozu-acme into the sozu command line
sozu-proxy/sozu pull request #862
Opened 2022-12-07 14:15 UTC by Keksoj

[sozu-acme](https://github.com/sozu-proxy/sozu-acme) is a configuration tool por Sōzu, that requests Let's Encrypt (or other ACME enabled authorities) to get certificates.

This PR takes the code of sozu acme and embeds it as a sōzu command line option:

```
sozu --config config.toml acme -h    
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/sozu --config config.toml acme -h`
Set up or renew Let's Encrypt certificates for sozu HTTP reverse proxy

Usage: sozu acme [OPTIONS] --config <CONFIG> --domain <DOMAIN> --email <EMAIL> --id <CLUSTER_ID> --new-cert <NEW_CERTIFICATE_PATH> --chain <CERTIFICATE_CHAIN_PATH> --key-path <KEY_PATH> --http <HTTP_FRONTEND_ADDRESS> --https <HTTPS_FRONTEND_ADDRESS>

Options:
      --config <CONFIG>
          Sets a custom config file
      --domain <DOMAIN>
          the application's domain name
  -t, --timeout <TIMEOUT>
          Sets a custom timeout for commands (in milliseconds). 0 disables the timeout
      --email <EMAIL>
          registration email
      --id <CLUSTER_ID>
          cluster identifier (usually an application)
      --old-cert <OLD_CERTIFICATE_PATH>
          path of the previous certificate (optional)
      --new-cert <NEW_CERTIFICATE_PATH>
          where to write the new certificate
      --chain <CERTIFICATE_CHAIN_PATH>
          where to write the certificate chain
  -k, --key-path <KEY_PATH>
          where to write the key
      --http <HTTP_FRONTEND_ADDRESS>
          HTTP frontend address, in the format IP:port
      --https <HTTPS_FRONTEND_ADDRESS>
          HTTPS frontend address, in the format IP:port
  -h, --help
          Print help information
```

2022-12-07 15:58 UTC, FlorentinDUBOIS requested changes

2022-12-07 15:58 UTC, FlorentinDUBOIS commented on bin/Cargo.toml
> +acme-lib = "^0.8"
Could you write the version entirely?

2022-12-07 15:58 UTC, FlorentinDUBOIS commented on bin/Cargo.toml
> +tiny_http = "^0.7"
Same here!

2022-12-07 15:58 UTC, FlorentinDUBOIS commented on bin/src/acme.rs
> +pub fn main(
I think the name could lead to misunderstanding

2022-12-07 16:00 UTC, FlorentinDUBOIS commented
Seems good to me, just the version number to keep track, it will allow to put an `=x.x.x` in case something break

2022-12-07 16:45 UTC, Keksoj commented on bin/Cargo.toml
> +acme-lib = "^0.8"
sure!

2022-12-08 13:59 UTC, FlorentinDUBOIS approved these changes

2022-12-08 13:59 UTC, merged