Refactor listeners socket addresses
sozu-proxy/sozu pull request #906
Opened 2023-03-29 13:52 UTC by Keksoj

In order to write these in protobuf:

- `HttpListenerConfig`
- `HttpsListenerConfig`
- `TcpListenerConfig`

We need to remove the `SocketAddr` types they contain and use `String` instead. Parsing to `SocketAddr` will be done a bit everywhere but only `String` will be passed between processes.

This PR also adds an `active` field on these listener configs. `active` is set to `false` by default, we need an `ActivateListener` request to set them to true.

2023-04-03 07:56 UTC, FlorentinDUBOIS requested changes

2023-04-03 07:56 UTC, FlorentinDUBOIS commented on lib/src/https.rs
> +        let public_address: std::net::SocketAddr = owned
Import SocketAddr properly here

2023-04-03 07:56 UTC, FlorentinDUBOIS commented on lib/src/https.rs
> +            .activate_listener(&address.parse().unwrap(), None)
There is a wild unwrap here

2023-04-03 07:57 UTC, FlorentinDUBOIS commented
There are few wild unwrap in the new source code that should be written differently

2023-04-03 11:36 UTC, Keksoj commented
Updated!

2023-04-04 09:44 UTC, FlorentinDUBOIS approved these changes
LGTM

2023-04-04 09:44 UTC, merged