add thiserror to sozu-command-lib
sozu-proxy/sozu pull request #966
Opened 2023-07-12 15:03 UTC by Keksoj

Using [anyhow](https://docs.rs/anyhow/latest/anyhow/index.html) in Sōzu has proven valuable to concatenate context accross function, and display the whole context all in one line for optimal readability.

This readability is only an advantage to humans, though. 

We aim to

2023-07-12 15:05 UTC, Keksoj commented
This is to solve this issue:

- #910

2023-07-21 09:46 UTC, FlorentinDUBOIS requested changes
Hey :wave: , I started the review, but I do not want to create a lot of comments. 
Could we avoid to
- Create items on error that ends with `Error`, it is redundant (aka `ChannerError::FooError`)
- Have generic message error like `IoError(std::io::Error)` and with a message like `read error`
- Create redendundant entries like (ClusterNotFound, ListenerNotFound and so on..), but instead have an error like `NotFound { kind: AnEnum, id: String }`

2023-07-21 09:46 UTC, FlorentinDUBOIS commented on command/src/channel.rs
> +    FromPathError { path: String, error: String },
Should be a `Connection` error

2023-07-21 09:46 UTC, FlorentinDUBOIS commented on command/src/channel.rs
> +    IoError(std::io::Error),
Too generic

2023-07-21 09:46 UTC, FlorentinDUBOIS commented on command/src/channel.rs
> +    #[error("channel buffer is full, cannot grow more, ignoring")]
```suggestion
    #[error("channel buffer is full, cannot grow more")]
```

2023-07-21 09:46 UTC, FlorentinDUBOIS commented on command/src/channel.rs
> +    Utf8Error(String),
```suggestion
    InvalidCharset(String),
```

2023-07-21 09:46 UTC, FlorentinDUBOIS commented on command/src/channel.rs
> +    #[error("Connection error, continuing")]
```suggestion
    #[error("Connection error")]
```

2023-07-21 09:46 UTC, FlorentinDUBOIS commented on command/src/config.rs
> +    AddressParsingError { address: String, error: String },
```suggestion
    ParseSocketAddr { address: String, error: String },
```

2023-07-21 09:46 UTC, FlorentinDUBOIS commented on command/src/scm_socket.rs
> +    Utf8Error(String),
```suggestion
    InvalidCharset(String),
```

2023-07-21 09:46 UTC, FlorentinDUBOIS commented on command/src/state.rs
> +    ListenerExistsAlready(String),
```suggestion
    Exists(String),
```

2023-07-21 09:46 UTC, FlorentinDUBOIS commented on command/src/state.rs
> +    NoListenerToRemove(String),
```suggestion
    NotFound(String),
```

2023-07-21 09:46 UTC, FlorentinDUBOIS commented on command/src/state.rs
> +    ClusterNotFound(String),
```suggestion
    NotFound(String),
```

2023-07-21 12:54 UTC, Keksoj commented
thanks @FlorentinDUBOIS , I removed all `...Error` endings in variants, it's more legible :+1: and I merged redundant error types in `NotFound` or `NoMetrics` variants.

2023-07-21 15:09 UTC, FlorentinDUBOIS requested changes
Nice works ! There are some stuffs to do, but we are quite close to merge it.

2023-07-21 15:09 UTC, FlorentinDUBOIS commented on command/src/config.rs
> +    InvalidField(String),
Should be an enum with error `Invalid` and kind `Field` and `Path`

2023-07-21 15:09 UTC, FlorentinDUBOIS commented on command/src/config.rs
> +    MissingField(String),
Should be an enum with error `NotFound` with kind `Field(string)`, `Protocol` and `SavedState`

2023-07-21 15:09 UTC, FlorentinDUBOIS commented on command/src/state.rs
> +    NotFound(String),
```suggestion
    NotFound(ObjectKind, string),
```
Am I missing a thing ?

2023-07-21 15:09 UTC, FlorentinDUBOIS commented on command/src/state.rs
> +    NoListenerToRemove(String),
redundant with `NoChange`

2023-07-21 15:09 UTC, FlorentinDUBOIS commented on lib/src/lib.rs
> +    FoundNoTcpCluster,
```suggestion
    NotFound(ObjectKind),
```

2023-07-21 15:09 UTC, FlorentinDUBOIS commented on lib/src/lib.rs
> +    PemParse(String),
```suggestion
    InvalidPem(String),
```

2023-07-21 15:09 UTC, FlorentinDUBOIS commented on lib/src/lib.rs
> +    SocketParse { address: String, error: String },
```suggestion
    InvalidSocketAddress { address: String, error: String },
```

2023-07-21 15:09 UTC, FlorentinDUBOIS commented on lib/src/metrics/mod.rs
> +    WrongUdpAddress { address: String, error: String },
```suggestion
    InvalidUdpAddress { address: String, error: String },
```

2023-07-21 15:09 UTC, FlorentinDUBOIS commented on lib/src/router/mod.rs
> +    PathRuleParse(String),
```suggestion
    InvalidPathRule(String),
```

2023-07-21 15:09 UTC, FlorentinDUBOIS commented on lib/src/router/mod.rs
> +    DomainParse { hostname: String },
```suggestion
    InvalidDomain { hostname: String },
```

2023-07-21 15:09 UTC, FlorentinDUBOIS commented on lib/src/socket.rs
> +    WrongAddress { address: String, error: String },
```suggestion
    InvalidSocketAddress { address: String, error: String },
```

2023-07-21 15:09 UTC, FlorentinDUBOIS commented on lib/src/tls.rs
> +    CommonNameParse(String),
Could you rename to 
```suggestion
    InvalidCommonName(String),
```

2023-07-21 15:09 UTC, FlorentinDUBOIS commented on lib/src/tls.rs
> +    PemParse(String),
```suggestion
    InvalidPem(String),
```

2023-07-21 15:09 UTC, FlorentinDUBOIS commented on lib/src/tls.rs
> +    DerParse(String),
```suggestion
    InvalidDer(String),
```

2023-07-21 15:26 UTC, Keksoj commented on command/src/channel.rs
> +            .map_err(|io_error| ChannelError::Connection(Some(io_error.to_string())))?;
Well, I find writing the error type in the clojure makes it very legible.

Or do you mean removing the `.to_string()` and implementing `From<IoError>` ?

2023-07-21 15:27 UTC, Keksoj commented on command/src/channel.rs
> +    Connection(Option<String>),
Sure !

2023-07-21 15:29 UTC, Keksoj commented on command/src/channel.rs
> +                    _other_error => {
very well if you insist

2023-07-21 15:32 UTC, Keksoj commented on command/src/state.rs
> +    NotFound(String),
I hope not, I'll take that into account

2023-07-25 14:31 UTC, Keksoj commented
this is ready for review BTW

2023-08-02 15:19 UTC, FlorentinDUBOIS approved these changes

2023-08-02 15:20 UTC, merged