Cluster related metrics, user-agent
sozu-proxy/sozu pull request #973
Opened 2023-08-02 14:28 UTC by hcaumeil

- Renaming gauge metrics that contains "count" in their name for consistency
- Make back-end HTTP status metrics,  5.x.x sozu HTTP status metrics and access_logs metric cluster-related (see #937 ).
- Add user agent in access logs (see #937 ).
- Add time metrics related to path rules / domain rules matching (see #804  ).

2023-08-02 14:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sozu-proxy/sozu?pullRequest=973) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sozu-proxy/sozu?pullRequest=973) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sozu-proxy/sozu?pullRequest=973) it.</sub>

2023-08-02 15:08 UTC, FlorentinDUBOIS requested changes

2023-08-02 15:08 UTC, FlorentinDUBOIS commented on doc/debugging_strategies.md
> +* `sozu.connections.errors`: could not connect to a backend server
for this one, we should keep the backend in name as it is related.

2023-08-02 17:12 UTC, Keksoj requested changes
This seems very okay. I request changes for variable naming and code presentation, for a better legibility.

Thank you for contributing!

2023-08-02 17:12 UTC, Keksoj commented on lib/src/http.rs
> +        res
please rename `res` to `result` (if present at all), `r` to `route`, and `c` to `cluster`.

2023-08-02 17:12 UTC, Keksoj commented on lib/src/http.rs
> +            .ok_or(FrontendFromRequestError::NoClusterFound);
I suggest doing:

```
        let route = self
            .fronts
            .lookup(host.as_bytes(), uri.as_bytes(), method)
            .ok_or_else(|| {
                incr!("http.failed_backend_matching");
                FrontendFromRequestError::NoClusterFound
            })?;
```
and drop the `if let Ok(route)` after.

2023-08-02 17:12 UTC, Keksoj commented on lib/src/https.rs
> +        res
same remarks as for `http.rs`

2023-08-02 17:12 UTC, Keksoj commented on lib/src/metrics/mod.rs
> +    {
nice

2023-08-02 17:12 UTC, Keksoj commented on lib/src/protocol/kawa_h1/mod.rs
> +                }
are we obligated to have all these additionnal curly brackets? They seem a bit overkill.
Just a cosmetic remark.

2023-08-02 17:12 UTC, Keksoj commented on lib/src/router/mod.rs
> +                res
`res` is mileading. Please rename to `is_a_match` or anything that conveys the idea of a boolean.

2023-08-02 17:12 UTC, Keksoj commented on lib/src/router/mod.rs
> +                if res {
same remark, please rename `res` to a more explicit name.

2023-08-03 11:31 UTC, Keksoj approved these changes
everything looks great to me now. Thanks!

2023-08-07 09:58 UTC, FlorentinDUBOIS commented on doc/debugging_strategies.md
> -* `sozu.backend.down`: the retry policy triggered and marked the backend server as down
Could you keep the `.backend` here also?

2023-08-08 16:54 UTC, FlorentinDUBOIS approved these changes

2023-08-08 16:59 UTC, merged