set rust-toolchain in bin to 1.70.0
sozu-proxy/sozu pull request #986
Opened 2023-09-04 08:32 UTC by Keksoj

Cloning and compiling the sozu binary would fail because of the `rust-toolchain` file introduced in c60f5ee5. One dependency needs version 1.70.0 when doing `cargo install --path .` in the workspace `bin`:

```
error: failed to compile `sozu v0.15.3 (/home/emmanuel/sozu/bin)`, intermediate artifacts can be found at `/home/emmanuel/sozu/target`

Caused by:
  package `clap_lex v0.5.1` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.67.0
  Either upgrade to rustc 1.70.0 or newer, or use
  cargo update -p clap_lex@0.5.1 --precise ver
  where `ver` is the latest version of `clap_lex` supporting rustc 1.67.0
```

2023-09-04 08:54 UTC, FlorentinDUBOIS commented
It miss the rust-version attribute in the cargo.toml file.

2023-09-04 08:56 UTC, FlorentinDUBOIS requested changes
You need to update the rust-version in the Cargo.toml file as well.

2023-09-04 08:56 UTC, FlorentinDUBOIS commented
Do you have check for other crate as well ?

2023-09-11 09:12 UTC, FlorentinDUBOIS requested changes

2023-09-11 09:12 UTC, FlorentinDUBOIS commented on bin/rust-toolchain
Could you move this file at the root of the repository and update every `Cargo.toml`'s field `rust-version`?
We could remove the other `rust-toolchain` if the override is working properly on sub-folder.

2023-09-11 12:59 UTC, Keksoj commented on bin/rust-toolchain
done!

2023-09-11 14:35 UTC, merged